version: "3"
services:

  mongo0:
    hostname: mongo0
    container_name: mongo0
    image: mongo
    ports:
      - 27017:27017
    restart: always
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=myUserAdmin
      # - MONGO_INITDB_ROOT_PASSWORD=abc123
      # - MONGO_INITDB_DATABASE=admin
    volumes:
      - ./configs:/docker-entrypoint-initdb.d
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs" ]

  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo
    ports:
      - 27018:27017
    restart: always
    # environment: 
      # - MONGO_INITDB_ROOT_USERNAME=myUserAdmin
      # - MONGO_INITDB_ROOT_PASSWORD=abc123
      # - MONGO_INITDB_DATABASE=admin
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs" ]
    
  mongo2:
    hostname: mongo2
    container_name: mongo2
    image: mongo
    ports:
      - 27019:27017
    restart: always
    # environment: 
      # - MONGO_INITDB_ROOT_USERNAME=myUserAdmin
      # - MONGO_INITDB_ROOT_PASSWORD=abc123
      # - MONGO_INITDB_DATABASE=admin
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs" ]
